### ISSUE TITLE
Queries need to be at least 4 characters in length

### ISSUE THREAD

**Issue by yoshielectron** [rorycl/cexfind#2]
Queries need to be at least 4 characters in length which limits being able to search for PS5, etc.

**Comment by yoshielectron** [comment]
MacBook 10,1 also results in Error: queries need to be at least 4 characters in length.

**Comment by rorycl** [comment]
@yoshielectron : thanks for this note. I hadn't thought there was any kit that only had a 3 character description! I'm going to make a separate issue for the "Macbook 10,1" issue since a comma is presently used to delimit separate queries.
