### ISSUE TITLE
Certain keywords return no results

### ISSUE THREAD

**Issue by yoshielectron** [rorycl/cexfind#7]
Certain keywords return no results even though the same search on webuy.com does return results. The issue was tested on the GCP version of the app and with both the strict option on and off. Example keywords that return no results:

sonic
terminator
dell
raspberry
windows

**Comment by rorycl** [comment]
Hi @yoshielectron. Thanks for the bug report.

I've just had a quick look at this. You are right! I thought it might be that the items you were searching for weren't available online, but that isn't the issue. That is [Terminator in stock online](https://uk.webuy.com/search?stext=terminator&availability=In+Stock+Online) returns over 100 hits.

The query I'm building to the API includes the following parameters:
```
clickAnalytics=true
facetFilters=[["availability:In Stock Online"]]
facets=["*"]
filters=boxVisibilityOnWeb=1 AND boxSaleAllowed=1
highlightPostTag=__/ais-highlight__
highlightPreTag=__ais-highlight__
hitsPerPage=17
maxValuesPerFacet=1000
page=0
tagFilters=
```
Perhaps the `boxSaleAllowed` parameter is the problem? I'll have to dig into this a bit.
